### ISSUE TITLE
Autoreply does not work with Postfix smtpd_sender_login_maps 

### ISSUE THREAD

**Issue by phaf** [modoboa/modoboa-postfix-autoreply#15]
According to the newest version of modoboa's documentation of Postfix maps [0], the configuration settings  _smtpd_sender_login_maps_ and _smtpd_sender_restrictions_ should be used.
If I enable them, the autoreply script is not allowed to send the reply mails. 

```
smtpd_sender_login_maps =
<driver>:/etc/postfix/sql-sender-login-mailboxes.cf
<driver>:/etc/postfix/sql-sender-login-aliases.cf
<driver>:/etc/postfix/sql-sender-login-domain-aliases.cf
<driver>:/etc/postfix/sql-sender-login-catchall-aliases.cf

smtpd_sender_restrictions =
reject_sender_login_mismatch
```

[0] https://github.com/tonioo/modoboa/blob/master/doc/integration/imap_and_smtp.rst

Any ideas on how those settings have  be configured in order to work with autoreply?

Thanks in advance.

**Comment by tonioo** [comment]
Hi,
you need to activate this feature only for the submission port (587), not globally.
