### ISSUE TITLE
Autoreply fail

### ISSUE THREAD

**Issue by minhvietbui** [modoboa/modoboa-postfix-autoreply#25]
Hi,
I have a problem with autoreply, becauce maximum charactors of address in  modoboa_admin_aliasrecipient table is 75. With email account as than.xuan@indochinadiscoverytravel.com when it create autoreply address in table is "than.xuan@indochinadiscoverytravel.com@autoreply.indochinadiscoverytravel.co". This isn't exact. How can I do to resolve  problem ? Thanks.

**Comment by tonioo** [comment]
Have you find a solution ?

**Comment by minhvietbui** [comment]
I change in mysql:  " alter table modoboa_admin_aliasrecipient modify column address varchar(255)", update address influence and now it ok.
