### ISSUE TITLE
Version 1.1.4 is called 1.1.3 in modoboa-core

### ISSUE THREAD

**Issue by kvdveer** [modoboa/modoboa-postfix-autoreply#31]
In `modoboa_postfix_autoreply/modo_extension.py` this project is still called 1.1.3, which triggers the update detection in modoboa. Not something to release a new version over, but just a reminder for 1.1.5 ;-)

**Comment by gawel** [comment]
https://github.com/modoboa/modoboa-postfix-autoreply/blob/master/modoboa_postfix_autoreply/modo_extension.py#L28

Maybe use `pkg_resources.get_distribution('modoboa_postfix_autoreply').version` instead of hard coded version
