### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by gawel** [modoboa/modoboa-postfix-autoreply#37]
Regarding http://www.postfix.org/VIRTUAL_README.html#autoreplies it seems that you dont have to always call the autoreply script

The script is called iif the mail has a vmap to an autoreply domain.

But modoboa seems to always call that script even if there is no autoreply to send. And this seems to cause some performances issues on our server.

Do you think that this can be avoid ?
Maybe by adding a temporary "autoreply" alias when the user set an autoreply ?

**Comment by tonioo** [comment]
Actually, the autoreply script is only called for users who have enabled their auto reply messages. (https://github.com/modoboa/modoboa-postfix-autoreply/blob/master/modoboa_postfix_autoreply/handlers.py#L81)

**Comment by gawel** [comment]
Fixed by repair https://github.com/modoboa/modoboa/pull/1042 Thanks
