### ISSUE TITLE
Date macro

### ISSUE THREAD

**Issue by HuTaeh** [modoboa/modoboa-postfix-autoreply#44]
Hello,

It would be nice to have the start and end dates of the automatic replies as a macro like the name macro.

**Comment by tonioo** [comment]
@HuTaeh What's your idea? The name macro is replaced by the account name but I don't see what would be appropriated for start and end dates...

**Comment by HuTaeh** [comment]
Hello,

The idea is to be able to use the dates configured in the "From" and "Until" fields as macro to avoid having to modify the message.
For example, a macro "untildate" that would be replaced by the date configured on the "Until" field.
Is it clearer ?

---

L'idée est d'avoir deux macros où chacune d'entre elle serait respectivement remplacé par les dates configurées dans les champs "From" et "Until".
Par exemple, une macro "untildate" qui serait remplacé par la date configuré dans le champs "Until".
Est-ce plus clair ?

**Comment by tonioo** [comment]
Ok, now I see :)
