### ISSUE TITLE
Autoreply error

### ISSUE THREAD

**Issue by lmfrazao** [modoboa/modoboa-postfix-autoreply#56]
when setting out of the office the sender gets this error:

No out-of-the office message is being send, the original message goes throug.

This is the mail system at host xxx.xxx.xxx.

I'm sorry to have to inform you that your message could not be delivered to one or more recipients. It's attached below.

For further assistance, please send mail to postmaster.

If you do so, please include this problem report. You can delete your own text from the attached returned message.

                   The mail system

<"xxx@xxx.xxx"@autoreply.xxx.xxx> (expanded from
    <xxx@xxx.xxx>): Command died with status 1:
    "/srv/modoboa/env/bin/python". Command output: Traceback (most recent call
    last):   File "/srv/modoboa/instance/manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)   File
    "/srv/modoboa/env/lib/python2.7/site-packages/django/core/management/__init__.py",
    line 364, in execute_from_command_line     utility.execute()   File
    "/srv/modoboa/env/lib/python2.7/site-packages/django/core/management/__init__.py",
    line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)   File
    "/srv/modoboa/env/lib/python2.7/site-packages/django/core/management/base.py",
    line 283, in run_from_argv     self.execute(*args, **cmd_options)   File
    "/srv/modoboa/env/lib/python2.7/site-packages/django/core/management/base.py",
    line 330, in execute     output = self.handle(*args, **options)   File
    "/srv/modoboa/env/lib/python2.7/site-packages/modoboa_postfix_autoreply/management/commands/autoreply.py",
    line 163, in handle     sender_localpart = split_mailbox(sender.lower())[0]
    File
    "/srv/modoboa/env/lib/python2.7/site-packages/modoboa/lib/email_utils.py",
    line 316, in split_mailbox     local_part, domain = split_address(mailbox)
    File
    "/srv/modoboa/env/lib/python2.7/site-packages/modoboa/lib/email_utils.py",
    line 269, in split_address     "address should be of type %s" %
    six.text_type.__name__ AssertionError: address should be of type unicode

**Comment by tonioo** [comment]
This issue has already been reported (see https://github.com/modoboa/modoboa-postfix-autoreply/pull/55).
