### ISSUE TITLE
autoreply and API

### ISSUE THREAD

**Issue by stefaweb** [modoboa/modoboa-postfix-autoreply#57]
Hi @tonioo!

Can we access autoreply with the Modoboa API?

Not found something related to autoreply in the API documentation.

I would like to develop an autoreply plugin for RoundCube using the API and Token.

Sincerely,

**Comment by stefaweb** [comment]
Hello folks!

Does someone know if the autoreply is implemented in the API? Or planned. ;)

Cheers,

**Comment by tonioo** [comment]
@stefaweb Hi, the autoreply module does not have an API right now. It is not something planned but we can think about it. What's your need?

**Comment by stefaweb** [comment]
Hi @tonioo!

I would like to code a driver for RoundCube rc-vacation plugin (https://github.com/bhuisgen/rc-vacation) as I've done for the password plugin.

Seems we need at minimum : 
```
%email = user email (or pk)
%vacation_enable = true/false
%vacation_subject = subject
%vacation_message = body
```

But we have all theses variables available:

```
	$search = array('%username',
					'%email_local',
					'%email_domain',
					'%email',
					'%vacation_enable',
					'%vacation_start',
					'%vacation_end',
					'%vacation_subject',
					'%vacation_message',
					'%vacation_keepcopyininbox',
					'%vacation_forwarder');
```

**Comment by stefaweb** [comment]
Hello @tonioo!

Any new on this. Do you need help?

**Comment by tonioo** [comment]
@stefaweb Hi, I need time...

**Comment by stefaweb** [comment]
Greatttttttttttt!
