### ISSUE TITLE
[Version 1.5.0] Problem of lookup with SQL table

### ISSUE THREAD

**Issue by mirtouf** [modoboa/modoboa-postfix-autoreply#61]
Bonjour,

After upgrade to version 1.5.0, it is no more possible to use the plugin as it prevents postfix to perform correctly its requests in the table sql-autoreplies-transport.cf
Here are some errors I got:
``38301:Oct  2 17:51:24 mail postfix/trivial-rewrite[2983]: warning: mysql:/etc/postfix/modoboa/sql-autoreplies-transport.cf lookup error for "*"``
``38302:Oct  2 17:51:24 mail postfix/trivial-rewrite[2983]: warning: mysql:/etc/postfix/modoboa/sql-autoreplies-transport.cf lookup error for "*"``
``38303:Oct  2 17:51:24 mail postfix/trivial-rewrite[2983]: warning: mysql:/etc/postfix/modoboa/sql-autoreplies-transport.cf lookup error for "*"``
``38304:Oct  2 17:51:24 mail postfix/trivial-rewrite[2983]: warning: mysql:/etc/postfix/modoboa/sql-autoreplies-transport.cf lookup error for "*"``
``118379:Oct  4 21:27:51 mail postfix/trivial-rewrite[29715]: warning: mysql:/etc/postfix/modoboa/sql-autoreplies-transport.cf lookup error for "bounce-debian-changes=mirtouf=mirtouf.net@lists.debian.org"``
``118381:Oct  4 21:27:51 mail postfix/trivial-rewrite[29715]: warning: mysql:/etc/postfix/modoboa/sql-autoreplies-transport.cf lookup error for "bounce-debian-changes=mirtouf=mirtouf.net@lists.debian.org"``
``118383:Oct  4 21:27:51 mail postfix/trivial-rewrite[29715]: warning: mysql:/etc/postfix/modoboa/sql-autoreplies-transport.cf lookup error for "mirtouf@mirtouf.net"``
``118385:Oct  4 21:27:51 mail postfix/trivial-rewrite[29715]: warning: mysql:/etc/postfix/modoboa/sql-autoreplies-transport.cf lookup error for "mirtouf@mirtouf.net"``

The upgrade process
``$ python manage.py migrate modoboa_postfix_autoreply``
``$ python manage.py collectstatic``
``$ python manage.py load_initial_data``
did not generate any error (I did not capture the output).

Can you advise of the possible actions to perform ?

**Comment by tonioo** [comment]
Please consult the documentation https://modoboa.readthedocs.io/en/latest/upgrade.html#modoboa-postfix-autoreply-1-5-0.
