### ISSUE TITLE
autoreply /api/v1/armessages/?search=user@domain.tld no longer works

### ISSUE THREAD

**Issue by stefaweb** [modoboa/modoboa-postfix-autoreply#66]
Hi @tonioo!

I just discovered that the access to autoreply message seems to have a bug. It was working in the past. The RoundCube plugin I wrote no longer works.

If we ask for: 

`https://modoboa/api/v1/armessages/?search=user@domain.tld`

We got many answers instead of one answer. 

As well with many answer, the RoundCube plugin is wrong. Same problem, when we try to write auto reply message to Modoboa with the RoundCube plugin.

Cheers,

**Comment by stefaweb** [comment]
Hi @tonioo!

No news from you. Busy ?

Stéphane

**Comment by tonioo** [comment]
@stefaweb yes... Actually, the search filter is not available.

**Comment by stefaweb** [comment]
When the filter will be back, what will be the right syntax ?

https://modoboa/api/v1/armessages/?mailbox=user@domain.tld
https://modoboa/api/v1/armessages/?account=user@domain.tld
https://modoboa/api/v1/armessages/?search=user@domain.tld
https://modoboa/api/v1/armessages/?mbox_user=user@domain.tld
https://modoboa/api/v1/armessages/?mbox=user@domain.tld

**Comment by tonioo** [comment]
Currently, the only available filters are ```mbox``` and ```mbox__user``` and they expect primary keys (id). I can add a search filter that will look for email addresses.

**Comment by stefaweb** [comment]
`https://modoboa/api/v1/armessages/?mbox=[value)` works but it is not the best as we need a first query to get the mbox id.

What is the right value to put in `https://modoboa/api/v1/armessages/?mbox_user=` ? I don't understand the use.

To found the record with email, the best syntax will be:

`https://modoboa/api/v1/armessages/?mailbox=user@domain.tld`
