### ISSUE TITLE
Autoreply error 

### ISSUE THREAD

**Issue by piensavirtual** [modoboa/modoboa-postfix-autoreply#68]
Good afternoon, I get an error, the auto-replace too, send me an undelivered with this

Action: failed
Status: 5.3.0
Diagnostic-Code: x-unix; Traceback (most recent call last):   File
    "/srv/modoboa/instance/manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)   File
    "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/__init__.py",
    line 364, in execute_from_command_line     utility.execute()   File
    "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/__init__.py",
    line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)   File
    "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/base.py",
    line 283, in run_from_argv     self.execute(*args, **cmd_options)   File
    "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/base.py",
    line 330, in execute     output = self.handle(*args, **options)   File
    "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa_postfix_autoreply/management/commands/autoreply.py",
    line 140, in handle     handler =
    SysLogHandler(address=options["syslog_socket_path"])   File
    "/usr/lib/python2.7/logging/handlers.py", line 761, in __init__
    self._connect_unixsocket(address)   File
    "/usr/lib/python2.7/logging/handlers.py", line 789, in _connect_unixsocket
    self.socket.connect(address)   File "/usr/lib/python2.7/socket.py", line
    228, in meth     return getattr(self._sock,name)(*args) socket.error:
    [Errno 111] Connection refused

Modoboa | 1.13.1 | 1.14.0 | El núcleo de Modoboa
-- | -- | -- | --
Frontend de Amavis | 1.2.3 | 1.2.3 | Panel de gestión sencilla para amavis
Contacts | 0.7.3 | 0.7.3 | Address book
DMARC tools | 1.1.0 | 1.1.0 | A set of tools to ease DMARC integration
IMAP migration using OfflineIMAP | 1.3.3 | 1.3.3 | Migrate existing mailboxes using IMAP and OfflineIMAP
PDF credentials | 1.3.2 | 1.3.2 | Generate PDF documents containing users' credentials
Postfix autoreply | 1.5.1 | 1.5.1 | Funcionalidad de autorespuesta (vacaciones) usando Postfix
Radicale management | 1.3.6 | 1.3.6 | Management frontend for Radicale, a simple calendar and contact server.
filtros Sieve | 1.4.2 | 1.4.2 | Extensión para crear filtros en el servidor de forma sencilla
Statistics | 1.4.1 | 1.4.1 | Estadísticas gráficas del tráfico de emails usando RRDtool
Webmail | 1.5.0 | 1.5.0 | Correo web sencillo para IMAP

**Comment by tonioo** [comment]
The script fails to connect to your syslog server. It will try `/dev/log` by default so make sure it's the right path, or change it using the `--syslog-socket-path` option.
