### ISSUE TITLE
Autoreply error (Header values can't contain newline)

### ISSUE THREAD

**Issue by whiteSpaceX** [modoboa/modoboa-postfix-autoreply#70]
Morning, since I updated to Modoboa 1.15 with Django 3.6 and Postfix-autoreply 1.6.0. I am getting this error sending emails to an account with autoreply on:

Remote Server returned 'XXX X.X.X < #5.3.0 x-unix; Traceback (most recent call last): File "/srv/modoboa/instance/manage.py", line 22, in <module> execute_from_command_line(sys.argv) File "/srv/modoboa/env/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line utility.execute() File "/srv/modoboa/env/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute self.fetch_command(subcommand).run_from_argv(self.argv) File "/srv/modoboa/env/lib/python3.7/site-packages/django/core/management/base.py", line 323, in run_from_argv self.execute(*args, **cmd_options) File "/srv/modoboa/env/lib/python3.7/site-packages/django/core/management/base.py", line 364, in execute output = self.handle(*args, **options) File "/srv/modoboa/env/lib/python3.7/site-packages/modoboa_postfix_autoreply/management/commands/autoreply.py", line 214, in handle send_autoreply(sender, mbox, armessage, original_msg) File "/srv/modoboa/env/lib/python3.7/site-packages/modoboa_postfix_autoreply/management/commands/autoreply.py", line 107, in send_autoreply msg.send() File "/srv/modoboa/env/lib/python3.7/site-packages/django/core/mail/message.py", line 291, in send return self.get_connection(fail_silently).send_messages([self]) File "/srv/modoboa/env/lib/python3.7/site-packages/django/core/mail/backends/smtp.py", line 110, in send_messages sent = self._send(message) File "/srv/modoboa/env/lib/python3.7/site-packages/django/core/mail/backends/smtp.py", line 124, in _send message = email_message.message() File "/srv/modoboa/env/lib/python3.7/site-packages/django/core/mail/message.py", line 275, in message msg[name] = value File "/srv/modoboa/env/lib/python3.7/site-packages/django/core/mail/message.py", line 169, in __setitem__ name, val = forbid_multi_line_headers(name, val, self.encoding) File "/srv/modoboa/env/lib/python3.7/site-packages/django/core/mail/message.py", line 60, in forbid_multi_line_headers raise BadHeaderError("Header values can't contain newlines (got %r for header %r)" % (val, name)) django.core.mail.message.BadHeaderError: Header values can't contain newlines (got '\n <AM0PR03MB553776DDF4AEA9363446D10FB94B0@AM0PR03MB5537.eurprd03.prod.outlook.com>' for header 'In-Reply-To')>'

**Comment by lmfrazao** [comment]
Hello, using modoboa 1.17 and python 3.6

still have this problem.

is there any way to fix this ?

update python to 3.7 or 3.8 can fix this ?

thank you.

**Comment by harryfoster** [comment]
Exact same thing for myself. I think it's only particular clients (Outlook?) and when replying to an email:
```
    "/srv/modoboa/env/lib64/python3.6/site-packages/django/core/mail/message.py",
    line 62, in forbid_multi_line_headers     raise BadHeaderError("Header
    values can't contain newlines (got %r for header %r)" % (val, name))
    django.core.mail.message.BadHeaderError: Header values can't contain
    newlines (got '\n
    <XXXYYYZZZ@XXXYYYZZZ.GBR1234.PROD.OUTLOOK.COM>'
    for header 'In-Reply-To')
```

Modoboa | 1.17.0
Postfix autoreply | 1.6.0

I think it gets incorporated at this location in /modoboa_postfix_autoreply/management/commands/autoreply.py:

    message_id = original_msg.get("Message-ID")
    if message_id:
        headers.update({"In-Reply-To": message_id, "References": message_id})

Outlook for some reason puts the Message_ID on new line, where as most other MTAs don't. We end up then carrying that /n over to the In-Reply-To header which Django doesn't like due to forbid_multi_line_headers. Maybe a quick newline strip() will sort this? This is just a quick glance, I haven't sat down with a debugger.

I'm going to experiment on my dev box.

**Comment by lmfrazao** [comment]
Still have that problem, only tested on outlook.

Luís Frazão | Bild Corp
+351 914120170
www.bild.pt
________________________________

**Comment by call2pedro** [comment]
I have same issue here at my box. Many times for Office 365 autoreply do not work as should and generates error as you mentioned.
